Uses GHA fromJSON and moves exit codes

diff --git a/.github/workflows/compile_extensions.yml b/.github/workflows/compile_extensions.yml
--- a/.github/workflows/compile_extensions.yml
+++ b/.github/workflows/compile_extensions.yml
@@ -48,35 +48,30 @@ jobs:
         ext-ref: ${{ matrix.value.ref }}
         
     - name: Extract Extension Info
-      uses: rgarcia-phi/json-to-variables@9835d537368468c4e4de5254dc3efeadda183793
-      with:
-        filename: ${{ matrix.value.path }}/ExtensionManifest.json
-        prefix: ext
-        masked: false
+      run: echo "manifest=$(cat ${{ matrix.value.path }}/ExtensionManifest.json)" >> $GITHUB_ENV
     
     - name: Debug Extension Info
       shell: bash
       run: |
         echo "[Extension Info Values]"
-        echo "Type                     : ${{ env.ext_type }}"
-        echo "Name                     : ${{ env.ext_name }}"
-        echo "Author                   : ${{ env.ext_author }}"
-        echo "GitHub Repository        : ${{ env.ext_repository }}"
-        echo "Package ID               : ${{ env.ext_packageId }}"
-        echo "Version                  : ${{ env.ext_version }}"
+        echo "Type                     : ${{ fromJSON(env.manifest).type }}"
+        echo "Name                     : ${{ fromJSON(env.manifest).name }}"
+        echo "Author                   : ${{ fromJSON(env.manifest).author }}"
+        echo "GitHub Repository        : ${{ fromJSON(env.manifest).repository }}"
+        echo "Package ID               : ${{ fromJSON(env.manifest).packageId }}"
+        echo "Version                  : ${{ fromJSON(env.manifest).version }}"
 
     - name: Validate Extension Info
       if: |
-        env.ext_type == '' || 
-        env.ext_name == '' || 
-        env.ext_author == '' || 
-        env.ext_repository == '' || 
-        env.ext_packageId == '' || 
-        env.ext_version == ''
+        fromJSON(env.manifest).type == '' || 
+        fromJSON(env.manifest).name == '' || 
+        fromJSON(env.manifest).author == '' || 
+        fromJSON(env.manifest).repository == '' || 
+        fromJSON(env.manifest).packageId == '' || 
+        fromJSON(env.manifest).version == ''
       shell: bash
       run: | 
-        echo "::error file=ExtensionManifest.json::Invalid manifest! Required attributes [version, type, packageId, target-plugin-api-version]"
-        exit 1
+        echo "::error file=ExtensionManifest.json::Invalid manifest! Required attributes [version, type, packageId, target-plugin-api-version]" && exit 1
         
     - name: Download a Build Artifact
       uses: actions/download-artifact@v3.0.2
@@ -103,5 +98,4 @@ jobs:
         fromJSON(steps.upload-build-files.outputs.response).success == 'false' &&
         fromJSON(steps.upload-build-files.outputs.response).errorCode != 4
       run: |
-        echo "::error ::Failed to upload files to build server. Response: ${{ steps.upload-build-files.outputs.response }}"
-        exit 1
+        echo "::error ::Failed to upload files to build server. Response: ${{ steps.upload-build-files.outputs.response }}" && exit 1
