Update extension_upsert.yml

diff --git a/.github/workflows/extension_upsert.yml b/.github/workflows/extension_upsert.yml
--- a/.github/workflows/extension_upsert.yml
+++ b/.github/workflows/extension_upsert.yml
@@ -56,7 +56,7 @@ jobs:
           if [ ! -d "./${{ env.output_path }}/${{ inputs.package_id }}" ]; then
             git submodule add "${{ inputs.github_http_url }}" "./${{ env.output_path }}/${{ inputs.package_id }}"
           else
-            git --git-dir "./${{ env.output_path }}/${{ inputs.package_id }}/.git" rev-parse HEAD | echo "::set-output name=current_hash::$(</dev/stdin)"
+            git --git-dir "./${{ env.output_path }}/${{ inputs.package_id }}/.git" rev-parse HEAD | echo "current_hash=$(</dev/stdin)" >> $GITHUB_ENV
           fi
           
       - name: Update Submodule
@@ -69,10 +69,10 @@ jobs:
       - name: Sanity Check
         run: |
           cd "./${{ env.output_path }}/${{ inputs.package_id }}"
-          if [ ! -z "${{ steps.add_submodule.current_hash }}" ]; then
-            git diff ${{ steps.add_submodule.current_hash }}..HEAD
-            git diff ${{ steps.add_submodule.current_hash }}..HEAD "ExtensionManifest.json" | grep "version" || echo "::error::ExtensionManifest.json 'version' key was not updated" && exit 1
-            git diff ${{ steps.add_submodule.current_hash }}..HEAD "./${{ env.output_path }}/${{ inputs.package_id }}/*.csproj" | grep "<Version>" || echo "::error::C# project file 'version' key was not updated" && exit 1
+          if [ ! -z "${{ env.CURRENT_HASH }}" ]; then
+            git diff ${{ env.CURRENT_HASH }}..HEAD
+            git diff ${{ env.CURRENT_HASH }}..HEAD "ExtensionManifest.json" | grep "version" || echo "::error::ExtensionManifest.json 'version' key was not updated" && exit 1
+            git diff ${{ env.CURRENT_HASH }}..HEAD "./${{ env.output_path }}/${{ inputs.package_id }}/*.csproj" | grep "<Version>" || echo "::error::C# project file 'version' key was not updated" && exit 1
           else
             git grep '"version"' -- "ExtensionManifest.json" || echo "::error::ExtensionManifest.json 'version' key does not exist" && exit 1
             git grep "<Version>" -- "./${{ env.output_path }}/${{ inputs.package_id }}/*.csproj" || echo "::error::C# project file 'version' key does not exist" && exit 1
