Update extension_upsert.yml

diff --git a/.github/workflows/extension_upsert.yml b/.github/workflows/extension_upsert.yml
--- a/.github/workflows/extension_upsert.yml
+++ b/.github/workflows/extension_upsert.yml
@@ -56,7 +56,7 @@ jobs:
           if [ ! -d "./${{ env.output_path }}/${{ inputs.package_id }}" ]; then
             git submodule add "${{ inputs.github_http_url }}" "./${{ env.output_path }}/${{ inputs.package_id }}"
           else
-            cd "./${{ env.output_path }}/${{ inputs.package_id }}" && echo "::set-output name=current_hash::$(git rev-parse HEAD)"
+            cd "./${{ env.output_path }}/${{ inputs.package_id }}" && git rev-parse HEAD | echo "::set-output name=current_hash::$(</dev/stdin)"
           fi
           
       - name: Update Submodule
@@ -74,7 +74,7 @@ jobs:
             git diff ${{ steps.add_submodule.current_hash }}..HEAD "ExtensionManifest.json" | grep "version" || echo "::error::ExtensionManifest.json 'version' key was not updated" && exit 1
             git diff ${{ steps.add_submodule.current_hash }}..HEAD "./${{ env.output_path }}/${{ inputs.package_id }}/*.csproj" | grep "<Version>" || echo "::error::C# project file 'version' key was not updated" && exit 1
           else
-            git grep "version" -- "ExtensionManifest.json" || echo "::error::ExtensionManifest.json 'version' key does not exist" && exit 1
+            git grep '"version"' -- "ExtensionManifest.json" || echo "::error::ExtensionManifest.json 'version' key does not exist" && exit 1
             git grep "<Version>" -- "./${{ env.output_path }}/${{ inputs.package_id }}/*.csproj" || echo "::error::C# project file 'version' key does not exist" && exit 1
           fi
           cd ../..
