Update extension_upsert.yml

diff --git a/.github/workflows/extension_upsert.yml b/.github/workflows/extension_upsert.yml
--- a/.github/workflows/extension_upsert.yml
+++ b/.github/workflows/extension_upsert.yml
@@ -51,9 +51,12 @@ jobs:
           git submodule update --init --recursive
           
       - name: Add Submodule (If Needed)
+        id: add_submodule
         run: | 
           if [ ! -d "./${{ env.output_path }}/${{ inputs.package_id }}" ]; then
             git submodule add "${{ inputs.github_http_url }}" "./${{ env.output_path }}/${{ inputs.package_id }}"
+          else
+            cd "./${{ env.output_path }}/${{ inputs.package_id }}" && echo "::set-output name=current_hash::$(git rev-parse HEAD)"
           fi
           
       - name: Update Submodule
@@ -66,9 +69,14 @@ jobs:
       - name: Sanity Check
         run: |
           cd "./${{ env.output_path }}/${{ inputs.package_id }}"
-          git diff
-          git diff "./${{ env.output_path }}/${{ inputs.package_id }}/ExtensionManifest.json" | grep "version" || echo "::error::ExtensionManifest.json 'version' key was not updated" && exit 1
-          git diff "./${{ env.output_path }}/${{ inputs.package_id }}/*.csproj" | grep "<Version>" || echo "::error::C# project file 'version' key was not updated" && exit 1
+          if [ ! -z "${{ steps.add_submodule.current_hash }}" ]; then
+            git diff ${{ steps.add_submodule.current_hash }}..HEAD
+            git diff ${{ steps.add_submodule.current_hash }}..HEAD "ExtensionManifest.json" | grep "version" || echo "::error::ExtensionManifest.json 'version' key was not updated" && exit 1
+            git diff ${{ steps.add_submodule.current_hash }}..HEAD "./${{ env.output_path }}/${{ inputs.package_id }}/*.csproj" | grep "<Version>" || echo "::error::C# project file 'version' key was not updated" && exit 1
+          else
+            git grep "version" -- "ExtensionManifest.json" || echo "::error::ExtensionManifest.json 'version' key does not exist" && exit 1
+            git grep "<Version>" -- "./${{ env.output_path }}/${{ inputs.package_id }}/*.csproj" || echo "::error::C# project file 'version' key does not exist" && exit 1
+          fi
           cd ../..
           
       - name: Create Pull Request
