Update extension_upsert.yml

diff --git a/.github/workflows/extension_upsert.yml b/.github/workflows/extension_upsert.yml
--- a/.github/workflows/extension_upsert.yml
+++ b/.github/workflows/extension_upsert.yml
@@ -65,13 +65,8 @@ jobs:
           
       - name: Sanity Check
         run: |
-          git diff "./${{ env.output_path }}/${{ inputs.package_id }}/ExtensionManifest.json" | grep "version"
-          extManifest=$?
-          git diff "./${{ env.output_path }}/${{ inputs.package_id }}/*.csproj" | grep "<Version>"
-          csProject=$?
-          if [ extManifest -ne 0 | csProject -ne 0]; then 
-            echo "::error::ExtensionManifest.json or C# project file 'version' key was not updated" && exit 1
-          fi
+          git diff "./${{ env.output_path }}/${{ inputs.package_id }}/ExtensionManifest.json" | grep "version" || echo "::error::ExtensionManifest.json 'version' key was not updated" && exit 1
+          git diff "./${{ env.output_path }}/${{ inputs.package_id }}/*.csproj" | grep "<Version>" || echo "::error::C# project file 'version' key was not updated" && exit 1
           
       - name: Create Pull Request
         uses: peter-evans/create-pull-request@v4
